ruby '>=2.3.1'
source 'https://rubygems.org'

# Middleman
gem 'middleman', '~> 4.3', '>= 4.3.8'
gem 'middleman-syntax', '~> 3.3', '>= 3.3.0'
gem 'middleman-autoprefixer', '~> 3.0', '>= 3.0.0'
gem 'middleman-sprockets', '~> 4.1'
gem 'rouge', '~> 3.2'
gem 'redcarpet', '~> 3.4.0'
gem 'nokogiri', '~> 1.10.8'
gem 'sass'
gem 'rack', '~> 2.2.19'
